# Generated by Django 3.2.5 on 2021-10-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
